buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.yaml:snakeyaml:2.2'
    }
}

import org.yaml.snakeyaml.Yaml

plugins {
    id 'java'
}

def versionYaml = new Yaml().load(file("version.yaml").text)
version = versionYaml["version"]

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}
