import org.yaml.snakeyaml.Yaml

plugins {
    id 'java'
}

def versionYaml = new Yaml().load(file("version.yaml").text)
version = versionYaml["version"]

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}
